name: build

on:
  workflow_dispatch:

jobs:
  ## Fill in Windows details at some point
  # mingw:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       arch: ["x86_64"]
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/cache@v3
  #       with:
  #         path: subprojects/packagecache
  #         key: ${{ hashFiles('subprojects/*.wrap') }}

  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y gcc-mingw-w64 meson nasm uuid-dev

  #     - name: Build
  #       run: |
  #         meson setup --cross-file=.ci/${{ matrix.arch }}-w64-mingw32.txt \
  #         ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_WIN }} builddir
  #         meson compile -vC builddir

  #     - name: Generate Win Mingw archives
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: q2pro-mingw-${{ matrix.arch }}
  #         path: |
  #           builddir/q2pro.exe
  #           builddir/q2proded.exe
  #           builddir/gamex86_64.dll

  linux64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          g++ -Wl,-rpath='$ORIGIN' -o aqtion -Wall -O0 -ggdb3 steamshim_parent.cpp -I sdk/public sdk/redistributable_bin/linux64/libsteam_api.so -no-pie
          strip aqtion
        env:
          CC: gcc

      - name: Set binary as executable
        run: |
          chmod +x aqtion
          
      - name: Generate Linux x64 archives
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-lin-gcc
          path: |
            aqtion

  # Do ARM build at some point
  # linuxARM64:
  #   runs-on: [self-hosted, ARM64]
  #   strategy:
  #     matrix:
  #       cc: [gcc]
  #   steps:
  #     - uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y meson libsdl2-dev libopenal-dev \
      #     libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev \
      #     libcurl4-gnutls-dev libx11-dev libxi-dev \
      #     libwayland-dev wayland-protocols libdecor-0-dev patchelf \
      #     libogg-dev libvorbis-dev

      # - name: Build
      #   run: |
      #     meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_LINUX }} builddir
      #     meson compile -vC builddir
      #   env:
      #     CC: ${{ matrix.cc }}

      # - name: Set binaries as executable
      #   run: |
      #     chmod +x builddir/q2pro*

      # - name: Generate Linux ARM archives
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: q2pro-lin-arm64
      #     path: |
      #       builddir/q2pro
      #       builddir/q2proded
      #       builddir/gamearm.so

  # darwin:
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       arch: [x86_64]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: |
  #         brew install pkg-config meson libpng sdl2 openal-soft zlib curl libvorbis jpeg-turbo

  #     - name: Build
  #       run: |
  #         meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_MAC }} builddir
  #         meson compile -vC builddir
  #       env:
  #         CC: "gcc"
  #         PKG_CONFIG_PATH: "/usr/local/opt/openal-soft/lib/pkgconfig"
  #         CFLAGS: "-mmacosx-version-min=10.7"

  #     - name: Set binaries as executable
  #       run: |
  #         chmod +x builddir/q2pro*

  #     - name: Generate Mac archives
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: q2pro-darwin-${{ matrix.arch }}
  #         path: |
  #           builddir/q2pro
  #           builddir/q2proded
  #           builddir/gamex86_64.dylib

  # Github does not support Apple Silicon yet
  # macARM64:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Homebrew for ARM64 and dependencies
  #       run: |
  #         arch -arm64 brew install meson libpng jpeg sdl2 openal-soft zlib curl libvorbis

  #     - name: Build
  #       run: |
  #         meson setup ${{ env.MESON_ARGS }} builddir
  #         ninja -vC builddir
  #       env:
  #         CC: "gcc"
  #         PKG_CONFIG_PATH: "/opt/homebrew/Cellar/openal-soft/1.22.2/lib/pkgconfig/:/opt/homebrew/Cellar/jpeg/9e/lib/pkgconfig/"
  #         CFLAGS: "-target arm64-apple-macos11"

  #     - name: Set binaries as executable
  #       run: |
  #         chmod +x builddir/q2pro*

  #     - name: Generate Mac archives
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: q2pro-mac-arm64
  #         path: |
  #           builddir/q2pro
  #           builddir/q2proded